// GENERATED FILE - do not edit by hand.
// Regenerate on Windows with: npm run generate:font-metrics  (scripts/generate-font-metrics.cjs)
//
// Metrics of the Windows fonts the preset font stacks resolve to, read from the font
// files: vertical metrics in font units and the unkerned advance width of every code
// point in ADVANCE_CODE_POINT_RANGES. Advances are two base-64 digits (DIGITS) each,
// in range order; '!!' marks a code point the font has no glyph for.

export type FaceMetrics = {
  unitsPerEm: number;
  winAscent: number;
  winDescent: number;
  hheaAscender: number;
  hheaDescender: number;
  hheaLineGap: number;
  advances: string;
};

export type FontMetricsEntry = { regular: FaceMetrics; bold: FaceMetrics };

export const ADVANCE_CODE_POINT_RANGES: ReadonlyArray<readonly [number, number]> = [
  [0x20, 0x7e],
  [0xa0, 0x17f],
  [0x2013, 0x2014],
  [0x2018, 0x2019],
  [0x201c, 0x201d],
  [0x2022, 0x2022],
  [0x2026, 0x2026],
  [0x20ac, 0x20ac],
  [0x2122, 0x2122],
];

export const ADVANCE_DIGITS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';

export const ADVANCE_MISSING = '!!';

export const FONT_METRICS: Readonly<Record<string, FontMetricsEntry>> = {
  Arial: {
    regular: {
      unitsPerEm: 2048,
      winAscent: 1854,
      winDescent: 434,
      hheaAscender: 1854,
      hheaDescender: -434,
      hheaLineGap: 67,
      advances:
        'I5I5LXRzRzcdVWGHKqKqMdSsI5KqI5I5RzRzRzRzRzRzRzRzRzRzI5I5SsSsSsRzgfVWVWXHXHVWTjY5XHI5QAVWRzaqXHY5VWY5XHVWTjXHVWeNVWVWTjI5I5I5PBRzKqRzRzQARzRzI5RzRzHHHHQAHHaqRzRzRzRzKqQAI5RzQAXHQAQAQAKsIUKsSsI5KqRzRzRzRzIURzKqXlL2RzSsKqXlRrMzRkKqKqKqScRMKqKqKqLsRzasasasTjVWVWVWVWVWVWgAXHVWVWVWVWI5I5I5I5XHXHY5Y5Y5Y5Y5SsY5XHXHXHXHVWVWTjRzRzRzRzRzRzcdQARzRzRzRzI5I5I5I5RzRzRzRzRzRzRzRkTjRzRzRzRzQARzQAVWRzVWRzVWRzXHQAXHQAXHQAXHQAXHTrXHRzVWRzVWRzVWRzVWRzVWRzY5RzY5RzY5RzY5RzXHRzXHRzI5I5I5I5I5I5I5HHI5I5XhONQAHHVWQAQARzHHRzHHRzJVRzKsRzHHXHRzXHRzXHRzTVXJRzY5RzY5RzY5RzgAeNXHKqXHKqXHKqVWQAVWQAVWQAVWQATjI5TjMATjI5XHRzXHRzXHRzXHRzXHRzXHRzeNXHVWQAVWTjQATjQATjQAHHRzgAHHHHKqKqLNgARzgA',
    },
    bold: {
      unitsPerEm: 2048,
      winAscent: 1854,
      winDescent: 434,
      hheaAscender: 1854,
      hheaDescender: -434,
      hheaLineGap: 67,
      advances:
        'I5KqPLRzRzcdXHHnKqKqMdSsI5KqI5I5RzRzRzRzRzRzRzRzRzRzKqKqSsSsSsTjfNXHXHXHXHVWTjY5XHI5RzXHTjaqXHY5VWY5XHVWTjXHVWeNVWVWTjKqI5KqSsRzKqRzTjRzTjRzKqTjTjI5I5RzI5cdTjTjTjTjMdRzKqTjRzY5RzRzQAMdI9MdSsI5KqRzRzRzRzI9RzKqXlL2RzSsKqXlRrMzRkKqKqKqScRzKqKqKqLsRzasasasTjXHXHXHXHXHXHgAXHVWVWVWVWI5I5I5I5XHXHY5Y5Y5Y5Y5SsY5XHXHXHXHVWVWTjRzRzRzRzRzRzcdRzRzRzRzRzI5I5I5I5TjTjTjTjTjTjTjRkTjTjTjTjTjRzTjRzXHRzXHRzXHRzXHRzXHRzXHRzXHRzXHXAXHTjVWRzVWRzVWRzVWRzVWRzY5TjY5TjY5TjY5TjXHTjXHTjI5I5I5I5I5I5I5I5I5I5ZHRzRzI5XHRzRzTjI5TjI5TjMVTjPVTjI5XHTjXHTjXHTjWrXJTjY5TjY5TjY5TjgAeNXHMdXHMdXHMdVWRzVWRzVWRzVWRzTjKqTjPVTjKqXHTjXHTjXHTjXHTjXHTjXHTjeNY5VWRzVWTjQATjQATjQAI5RzgAI5I5QAQALNgARzgA',
    },
  },
  Candara: {
    regular: {
      unitsPerEm: 2048,
      winAscent: 1950,
      winDescent: 550,
      hheaAscender: 1484,
      hheaDescender: -564,
      hheaLineGap: 452,
      advances:
        'G8IEOeQJONQJV0IJLTLTQJQJIEIEIEIjRlLMOyPjREPuRqPIRnRjIEIEQJQJQJLTgSTuSwRlUkQqPqT3U3I2NTS8PrbUVkWNRsWNTYQXQTV2RucXR3RnQmLTIjLTQJQJIyPtRyOdRnQbK2RRRVG+G+PoHVaNRVR4RyRzLWNaLfRJPYYhQIO4OlLTIELTQJG8IEQJONPoONIENbNEUeJpOhQJIEUeH0IjQJIjIjIyRoVbIEHWIjJpOhYOYOYOLTTuTuTuTuTuTuaERlQqQqQqQqI2I2I2I2UkVkWNWNWNWNWNQAWNV2V2V2V2RnRsRPPtPtPtPtPtPtZMOdQbQbQbQbG+G+G+G+RiRVR4R4R4R4R4QJR4RJRJRJRJO4R2O4TuPtTuPtTuPtRlOdRlOdRlOdRlOdUkT+UkRwQqQbQqQbQqQbQqQbQqQbT3RRT3RRT3RRT3RRU3RVU3RVI2G+I2G+I2G+I2G+I2G+WTN8NTG+S8PoPoPrHVPrHwPrJoPrKqPrJEVkRVVkRVVkRVULVkRbWNR4WNR4WNR4c2bmTYLWTYLWTYLWQXNaQXNaQXNaQXNaQTLfQTORQTLfV2RJV2RJV2RJV2RJV2RJV2RJcXYhRnO4RnQmOlQmOlQmOlI2QAgAIEIEQJQJVHgAONVS',
    },
    bold: {
      unitsPerEm: 2048,
      winAscent: 1950,
      winDescent: 550,
      hheaAscender: 1484,
      hheaDescender: -564,
      hheaLineGap: 452,
      advances:
        'G8IEOoQJONQJV0IELTLTQJQJIEIEIEIjRGKtPWPERLPJQ7O4RKQ5IEIEQJQJQJLTgSUKTIRrUpQ4PtT5U6I7MyS3PibpVRWTRyWTTEQvQ1VDSXdVSzRqQeLTIjLTQJQJIyPuRwOQRnQZLlRoRmH+H+QVIQaoRmR4R6RwMVNbLnRTPqZNQfPqN6LTIELTQJG8IEQJONPoONH0NbNEVJI+OhQJIEVJH0IjQJIjIjIyRoVbIEHWIjJ9OhYOYOYOLTUKUKUKUKUKUKafRrQ4Q4Q4Q4I7I7I7I7UpVRWTWTWTWTWTQAWTVDVDVDVDRqRyRYPuPuPuPuPuPuZLOQQZQZQZQZH+H+H+H+RqRmR4R4R4R4R4QJR4RTRTRTRTPqRwPqUKPuUKPuUKPuRrOQRrOQRrOQRrOQUpU+UpRwQ4QZQ4QZQ4QZQ4QZQ4QZT5RoT5RoT5RoT5RoU6RmU6RmI7H+I7H+I7H+I7H+I7H+VtP8McH+S3QVQVPiIQPiIQPiLaPiMLPiKAVRRmVRRmVRRmWmVRRmWTR4WTR4WTR4dHblSjMVSjMVSjMVQZNbQZNbQvNbQZNbQ1LnQ1O4Q1LnVDRTVDRTVDRTVDRTVDRTVDRTdVZNRqPqRqQeN6QeN6QeN6JAQAgAIEIEQJQJVHgAONV/',
    },
  },
  Calibri: {
    regular: {
      unitsPerEm: 2048,
      winAscent: 1950,
      winDescent: 550,
      hheaAscender: 1536,
      hheaDescender: -512,
      hheaLineGap: 452,
      advances:
        'HPKbM1P8QOW4V1HEJtJtP8P8H/JzIFMXQOQOQOQOQOQOQOQOQOQOIkIkP8P8P8O1cnShRaRETsPoOtUMT8IEKNQoNdbXUqVMQiViRYOtPmUiSKceQnPmO/J0MXJ0P8P8JUPVQ0NiQ0P7JxPEQ0HWHqOjHWZkQ0Q4Q0Q0LKMhKuQ0OdW4N3OfMpKEOvKEP8HPKbP8QOP8QOP8P8MkatM4QZP8JzQOMnK2P8KwKtJWRmSwIFJ1H4NhQZUXVfVnO1ShShShShShShYbREPoPoPoPoIEIEIEIET/UqVMVMVMVMVMP8VPUiUiUiUiPmQiQ4PVPVPVPVPVPVYvNiP7P7P7P7HWHWHWHWQ0Q0Q4Q4Q4Q4Q4P8Q8Q0Q0Q0Q0OfQ0OfShPVShPVShPVRENiRENiRENiRENiTsSMT/RqPoP7PoP7PoP7PoP7PoP7UMPEUMPEUMPEUMPET8Q0VARDIEHWIEHWIEHWIEHWIEHWSSPAKNHqQoOjOjNdHWNdHWNiIcReL9NwH7UqQ0UqQ0UqQ0SiUHQ0VMQ4VMQ4VMQ4bvbMRYLKRYLKRYLKOtMhOtMhOtMhOtMhPmKuPmLEPmK8UiQ0UiQ0UiQ0UiQ0UiQ0UiQ0ceW4PmOfPmO/MpO/MpO/MpHxP8c+H/H/NZNZP8WGQOWk',
    },
    bold: {
      unitsPerEm: 2048,
      winAscent: 1950,
      winDescent: 550,
      hheaAscender: 1536,
      hheaDescender: -512,
      hheaLineGap: 452,
      advances:
        'HPKbOCP8QOXVWjHeJ+J+P8P8IQJzIjNwQOQOQOQOQOQOQOQOQOQOI1I1P8P8P8O1cwTZR8Q8ULPnOsUZUMIiKmRgNib+VFVpRCV9SBPIP2U5S7dARoQoPTKZNwKZP8P8JnPzRLNZRLQHKIPLRLH3ILPXH3aCRLRNRLRLLYMxLGRLPJX2OtPKMuLAPNLAP8HPKbP8QOP8QOP8P8NRatNURPP8JzQOMfK9P8K0KwJoSCTIIkJtIFN7RPVDWHWdO1TZTZTZTZTZTZY0Q8PnPnPnPnIiIiIiIiUdVFVpVpVpVpVpP8VyU5U5U5U5QoRCRwPzPzPzPzPzPzYzNZQHQHQHQHH3H3H3H3RLRLRNRNRNRNRNP8RaRLRLRLRLPKRLPKTZPzTZPzTZPzQ8NZQ8NZQ8NZQ8NZULTGUdSNPnQHPnQHPnQHPnQHPnQHUZPLUZPLUZPLUZPLUMRLVDRhIiH3IiH3IiH3IiH3IiH3TJQDKmILRgPXPXNiH3NiH3NxJzR+NhN2IcVFRLVFRLVFRLT6UhRLVpRNVpRNVpRNb+a+SBLYSBLYSBLYPIMxPIMxPIMxPIMxP2LGP2LoP2LWU5RLU5RLU5RLU5RLU5RLU5RLdAX2QoPKQoPTMuPTMuPTMuIRP8c+IQIQN7N7P8WxQOXD',
    },
  },
  Corbel: {
    regular: {
      unitsPerEm: 2048,
      winAscent: 1950,
      winDescent: 550,
      hheaAscender: 1523,
      hheaDescender: -525,
      hheaLineGap: 425,
      advances:
        'GaIdLmU9QaZwVbGRJmJmRNQaIcKpIdIzQcOWQWOgQiPXQyNsQeQyIdIiQaQaQaNpgWUVS/S3VeRpQJVYVXH3L/TXQqaTWSXYSQXqS8RqRxVeTbcOSsTBSvKGIzKGQaPoK8PrRJOCRJP7KLQ/RCHbHuPlHbahQ4REQ/QwKuM8LHQkOyWyOkPWOOJnHRJnQaGaIdQaQaQaQaHRNpK8aWMJPlQaKpT2K8NEQaKBJeK8ScSgIdK8J3NGPlaGbwY4NpUVUVUVUVUVUVcWS3RpRpRpRpH3H3H3H3V8WSXYXYXYXYXYQaXYVeVeVeVeTBSKTgPrPrPrPrPrPrY4OCP7P7P7P7HbHbHbHbQ1Q4REREREREREQaREQkQkQkQkPWQ/PWUVPrUVPrUVPrS3OCS3OCS3OCS3OCVeRJV8RJRpP7RpP7RpP7RpP7RpP7VYQ/VYQ/VYQ/VYQ/VXRCVXRCH3HbH3HbH3HbH3HbH3HbSrPJL/HuTXPlPbQqHbQqHbQqHbQqJ+QqHbWSQ4WSQ4WSQ4Q4WSQ4XYREXYREXYREhzbfS8KuS8KuS8KuRqM8RqM8RqM8RqM8RxLHRxLHRxLHVeQkVeQkVeQkVeQkVeQkVeQkcOWyTBPWTBSvOOSvOOSvOOJJPoakHBHBMpMpOMZXQabY',
    },
    bold: {
      unitsPerEm: 2048,
      winAscent: 1950,
      winDescent: 550,
      hheaAscender: 1523,
      hheaDescender: -525,
      hheaLineGap: 425,
      advances:
        'GmJXMoVRQ4aeWJGvJyJyQ5Q4KJKpJXJbQfP1P+PnQ5PqRnPoRyRoJXKJQ4Q4Q4OYgyVCT8StWDSLQrVhWWI1M4UORNacXSXgTOYVUGSeSQWaUadIUWUTTPKGJbKGQ4PoMgQeR1OHR2QaKgRmR6H9IaQhIFbRRwRuRmRmLMNkMJRcPuX+QsQcO+JxHlJxQ4GmJXQ4Q4Q4Q4HlOYMgaWMvQcQ4KpT2MgNEQ4KvKQMgScTIJXMgK3NsQcbDc8Z1OYVCVCVCVCVCVCd5StSLSLSLSLI1I1I1I1XLXSXgXgXgXgXgQ4XgWaWaWaWaUTTOT5QeQeQeQeQeQeZjOHQaQaQaQaH9H9H9H9RcRwRuRuRuRuRuQ4RuRcRcRcRcQcRmQcVCQeVCQeVCQeStOHStOHStOHStOHWDR2XLR2SLQaSLQaSLQaSLQaSLQaVhRmVhRmVhRmVhRmWWR6WWR6I1H9I1H9I1H9I1H9I1H9U5P+M4IaUOQrQhRNIFRNIFRNIFRNL+RNIFXSRwXSRwXSRwRwXSRwXgRuXgRuXgRuhgbzUGLMUGLMUGLMSeNkSeNkSeNkSeNkSQMJSQMJSQMJWaRcWaRcWaRcWaRcWaRcWaRcdIX+UTQcUTTPO+TPO+TPO+JgPoakHxHxOkOkOMcFQ4bY',
    },
  },
  Bahnschrift: {
    regular: {
      unitsPerEm: 2048,
      winAscent: 2036,
      winDescent: 422,
      hheaAscender: 1626,
      hheaDescender: -422,
      hheaLineGap: 410,
      advances:
        'ImIqMHT+SdV/U3FsK3K3NxQ6HQPWHQMHRqKpQiQ7SNRbQbQHSAQbHQHQNlOsNvN0cfUuUqTzVATIR5UsVuI0QLUiSWY8WaUqT7VCU3TtPaU+SybGSKQGRaJaMHJaQGN8JbRCRaP8RQRKKJRQR4ICIlQ7JRbaR4RcRaRQNqQmKcRzQAYwQjPdP1LiI0LiQcImIqPUS8SaQGI0ScMaWWLBQFQuPWWWN6LqQ6KAKwJbTDWEGyJGHxK8QFV5VtWhNMUuUuUuUuUuUufQTzTITITITII0I0I0I0VvWaUqUqUqUqUqQHUqU+U+U+U+QGT7RxRCRCRCRCRCRCasP8RKRKRKRKICICICICROR4RcRcRcRcRcPcRcRzRzRzRzPdRaPdUuRCUuRCUuRCTzP8!!!!TzP8TzP8VAUiVvRQTIRK!!!!TIRKTIRKTIRK!!!!UsRQUsRQUsRQ!!!!YOSPI0ICI0IC!!!!I0ICI0IC!!!!!!!!UiQ7!!SWJRSWJRSWLx!!!!TwJRWaR4WaR4WaR4!!WaR4UqRc!!!!UqRcgFbMU3NqU3NqU3NqTtQm!!!!TtQmTtQmPaKcPaMU!!!!U+RzU+RzU+RzU+RzU+RzU+Rz!!!!!!!!QGRaP1RaP1RaP1!!R2bZFsFsKOKOI3SqUKVN',
    },
    bold: {
      unitsPerEm: 2048,
      winAscent: 2036,
      winDescent: 422,
      hheaAscender: 1626,
      hheaDescender: -422,
      hheaLineGap: 410,
      advances:
        'ImIqMHT+SdV/U3FsK3K3NxQ6HQPWHQMHRqKpQiQ7SNRbQbQHSAQbHQHQNlOsNvN0cfUuUqTzVATIR5UsVuI0QLUiSWY8WaUqT7VCU3TtPaU+SybGSKQGRaJaMHJaQGN8JbRCRaP8RQRKKJRQR4ICIlQ7JRbaR4RcRaRQNqQmKcRzQAYwQjPdP1LiI0LiQcImIqPUS8SaQGI0ScMaWWLBQFQuPWWWN6LqQ6KAKwJbTDWEGyJGHxK8QFV5VtWhNMUuUuUuUuUuUufQTzTITITITII0I0I0I0VvWaUqUqUqUqUqQHUqU+U+U+U+QGT7RxRCRCRCRCRCRCasP8RKRKRKRKICICICICROR4RcRcRcRcRcPcRcRzRzRzRzPdRaPdUuRCUuRCUuRCTzP8!!!!TzP8TzP8VAUiVvRQTIRK!!!!TIRKTIRKTIRK!!!!UsRQUsRQUsRQ!!!!YOSPI0ICI0IC!!!!I0ICI0IC!!!!!!!!UiQ7!!SWJRSWJRSWLx!!!!TwJRWaR4WaR4WaR4!!WaR4UqRc!!!!UqRcgFbMU3NqU3NqU3NqTtQm!!!!TtQmTtQmPaKcPaMU!!!!U+RzU+RzU+RzU+RzU+RzU+Rz!!!!!!!!QGRaP1RaP1RaP1!!R2bZFsFsKOKOI3SqUKVN',
    },
  },
  'Sitka Text': {
    regular: {
      unitsPerEm: 2250,
      winAscent: 2580,
      winDescent: 670,
      hheaAscender: 1703,
      hheaDescender: -547,
      hheaLineGap: 563,
      advances:
        'KBMIRPXkSsjfYmKJO+O+S+XkKYNdKYQmWYQIUDTvVJTpVHTeV6VHMbMbXkXkXkRSixWnWOWSY3WKUWYqa8NAM5XgUbfxa2Y7UeZAXRTxWAZyWwikWyV2UfO3QmO3XkTMQAS+UHQ2UeSVNDTTU/LZLZTwLFfiVRTnUpUIQDQbNWU3TMdbTXTDRPQwQmQwXkKBMIUIVoSiWsQmVFQAfQRgVuXkNdfQ!!QAXkNyN0QAVOVZKsQALORlVudgfqfFRSWnWnWnWnWnWniDWSWKWKWKWKNANANANAY3a2Y7Y7Y7Y7Y7XkY7ZyZyZyZyV2UeWoS+S+S+S+S+S+crQ2SVSVSVSVLZLZLaLaTQVRTnTnTnTnTnXkTnU3U3U3U3TDULTDWnS+WnS+WnS+WSQ2WSQ2WSQ2WSQ2Y3XiY3UeWKSVWKSVWKSVWKSVWKSVYqTTYqTTYqTTYqTTa8U/a8U/NALZNALZNALZNALZNALZZ4WxM5LZXgTwUbUbLFUbLFUbN0UbNFUbLFa2VRa2VRa2VRbRa2VPY7TnY7TnY7TniLe6XRQDXRQDXRQDTxQbTxQbTxQbTxQbWANWWANWWANWZyU3ZyU3ZyU3ZyU3ZyU3ZyU3ikdbV2TDV2UfRPUfRPUfRPL5TMciJqJqQxQxN5fKVBdH',
    },
    bold: {
      unitsPerEm: 2250,
      winAscent: 2580,
      winDescent: 670,
      hheaAscender: 1703,
      hheaDescender: -547,
      hheaLineGap: 563,
      advances:
        'KBNYTIX6W1lfabK7QQQQTDX6LTNZLTRCWpQWUuUeVtUcVtTfWmVuNSNSX6X6X6SHiGXyXuWYZ7XrVrZicXOVOOZbVohcbXZhWPZlY1VOXLalYBjBYAXJVUQKRCQKX6TMQAUGVTQ9VxTBOPUeWaMjMkVMMQg+WsUvV7VURQR3OeWSUFeAUhUKSSSERCSEX6KBNYU5WiSiWfRCWWQAfKSwWuX6NZfQ!!QYX6O/PLQAWkWiLjQAMcSkWuggfqiKSHXyXyXyXyXyXyjzWYXrXrXrXrOVOVOVOVZ7bXZhZhZhZhZhX6ZhalalalalXJWPYKUGUGUGUGUGUGdYQ9TBTBTBTBMjMjMkMkURWsUvUvUvUvUvX6UvWSWSWSWSUKVcUKXyUGXyUGXyUGWYQ9WYQ9WYQ9WYQ9Z7WxZ7VxXrTBXrTBXrTBXrTBXrTBZiUeZiUeZiUeZiUecXWacXWaOVMjOVMjOVMjOVMjOVMjcjZHOOMkZbVMVMVoMQVoMQVoQCVoQ9VoMQbXWsbXWsbXWsedbXWpZhUvZhUvZhUvj9fWY1RQY1RQY1RQVOR3VOR3VOR3VOR3XLOeXLOeXLOealWSalWSalWSalWSalWSalWSjBeAXJUKXJVUSSVUSSVUSSNETdczKkKkSZSZO+h5Wdcp',
    },
  },
  'Palatino Linotype': {
    regular: {
      unitsPerEm: 2048,
      winAscent: 2150,
      winDescent: 613,
      hheaAscender: 1499,
      hheaDescender: -582,
      hheaLineGap: 682,
      advances:
        'IAI5L4PVQAa4Y5GqKqKqMdQAIAKqIAKQQAQAQAQAQAQAQAQAQAQAIAIAQAQAQAONV3Y5TjWsYxTjRzYbaoKyKqXPTjeRamZKTVZKVYQzTnY5XHgAVWVWVWKqTZKqQAQAKqQARtONTjPVKqRzSoJUHfRzJUcQSoReTPR7MpNkKcTTSFasQhRzQAKqQAKqQAIAI5QAQAQAQAQAQAKqX6KqQAQAKqX6KqMzQAKPKPKqUtUGIAKqKPKqQAZ0Z0Z0ONY5Y5Y5Y5Y5Y5eNWsTjTjTjTjKyKyKyKyYxamZKZKZKZKZKQAaqY5Y5Y5Y5VWTVRzQAQAQAQAQAQAYQONPVPVPVPVJUJUJUJUReSoReReReReReQAReTTTTTTTTRzTPRzY5QAY5QAY5QAWsONWsONWsONWsONYxVjYxTjTjPVTjPVTjPVTjPVTjPVYbRzYbRzYbRzYbRzaoSoaoSoKyJUKyJUKyJUKyJUKyJUVcQNKqHfXPRzQxTjJUTjJUTjLwTjK5TjJUamSoamSoamSoXFamSDZKReZKReZKRef8aeVYMpVYMpVYMpQzNkQzNkQzNkQzNkTnKcTnLyTnKcY5TTY5TTY5TTY5TTY5TTY5TTgAasVWRzVWVWQAVWQAVWQAKqQAgAI5I5QAQATZgAQAfV',
    },
    bold: {
      unitsPerEm: 2048,
      winAscent: 2150,
      winDescent: 613,
      hheaAscender: 1499,
      hheaDescender: -582,
      hheaLineGap: 682,
      advances:
        'IAI5MVPaQAcdaqHRKqKqONQAIAKqIAJeQAQAQAQAQAQAQAQAQAQAIAIAQAQAQAONWUY5VJXHamTZR2aqaqMdMdYoTZgAaqaqTiaqW2TjVWY5Y5gAVWVWVWKqJeKqQAQAKqQATjONTjQAMdRyTjKqKqTjKqcdTjRzTjTjMdONKqTjRyaqQARzQAJ7QAJ7QAIAI5QAQAQAQAQAQAKqX6JaQAQAKqX6KqMzQAKSKSKqVnUhIAKqKSKdQAZ7Z7Z7ONY5Y5Y5Y5Y5Y5gAXHTZTZTZTZMdMdMdMdamaqaqaqaqaqaqQAaqY5Y5Y5Y5VWTjTjQAQAQAQAQAQAY5ONQAQAQAQAKqKqKqKqRzTjRzRzRzRzRzQARzTjTjTjTjRzTjRzY5QAY5QAY5QAXHONXHONXHONXHONamXBamTjTZQATZQATZQATZQATZQAaqRyaqRyaqRyaqRyaqTjaqTjMdKqMdKqMdKqMdKqMdKqYVUaMdKqYoTjSjTZKqTZKqTZN0TZNvTZKqaqTjaqTjaqTjZiaqTUaqRzaqRzaqRzgAaqW2MdW2MdW2MdTjONTjONTjONTjONVWKqVWNtVWKqY5TjY5TjY5TjY5TjY5TjY5TjgAaqVWRzVWVWQAVWQAVWQAMdQAgAI5I5QAQATZgAQAf8',
    },
  },
  'Courier New': {
    regular: {
      unitsPerEm: 2048,
      winAscent: 1705,
      winDescent: 615,
      hheaAscender: 1705,
      hheaDescender: -615,
      hheaLineGap: 0,
      advances:
        'TNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTN',
    },
    bold: {
      unitsPerEm: 2048,
      winAscent: 1705,
      winDescent: 615,
      hheaAscender: 1705,
      hheaDescender: -615,
      hheaLineGap: 0,
      advances:
        'TNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTNTN',
    },
  },
};
